version: "2"
services:
  mariadb:
    image: mariadb
    ports:
      - "8081:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
  wordpress:
    image: wordpress
    volumes:
      - ./public:/var/www/html
    ports:
      - "8080:80"
    links:
      - mariadb:mysql
    environment:
      WORDPRESS_DB_PASSWORD: root
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8082:80
    links:
      - mariadb:mysql
    environment:
      PMA_USER: root
      PMA_PASSWORD: root
      PMA_HOST: mysql
